
let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Swiss Cheese",
    price: 45,
    desc: "Monstera deliciosa is commonly grown outdoors as an ornamental plant in the tropics and subtropics.",
    img: "images/img-1.jpeg",
  },
  {
    id: "ioytrhndcv",
    name: "Ficus Elastica",
    price: 100,
    desc: "An excellent choice for an air purifying as well as an ornamental plant, it thrives in the Indian climate.",
    img: "images/img-2.jpeg",
  },
  {
    id: "wuefbncxbsn",
    name: "Calathea Lancifolia",
    price: 25,
    desc: "Calathea Lancifolia Insignis Rare Natural Live Prayer Low Maintenance Plants Indoor|Outdoor Indoor & Garden.",
    img: "images/img-3.jpeg",
  },
  {
    id: "thyfhcbcv",
    name: "Fiddle Leaf Fig",
    price: 300,
    desc: "The fiddle-leaf fig is a popular indoor plant, but can also grow outdoors. ",
    img: "images/img-4.jpeg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Pothos",
    price: 25,
    desc: "Potus plant, which is a tropical evergreen climbing plant with fine stems that can grow up to 20 meters long. ",
    img: "images/img-5.jpeg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Monstera Adansonii",
    price: 200,
    desc: "Monstera adansonii is known for its beautiful heart-shaped leaves. ",
    img: "images/img-6.jpeg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Areca Palm",
    price: 450,
    desc: "Also known as the bamboo palm, the areca palm (Dypsis lutescens) is one of the easiest palms to grow indoors.",
    img: "images/img-7.jpeg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: " Pothos variegated",
    price: 45,
    desc: "This variegated pothos is characterized by medium green foliage",
    img: "images/img-8.jpeg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "ZZ plant",
    price: 85,
    desc: " ZZ plants (Zamioculcas zamiifolia), or Zanzibar gems, are drought-tolerant plants that are staples in homes.",
    img: "images/img-9.jpeg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Pilea ",
    price: 120,
    desc: " The Pilea Peperomioides, also known as the Chinese Money Plant, is an eye-catching green beauty.",
    img: "images/img-10.jpeg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Mini Monstera",
    price: 35,
    desc: " Mini monstera grow best with several hours of bright, indirect light every day.",
    img: "images/img-11.jpeg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Bamboo Palm",
    price: 350,
    desc: "Bamboo palms are effective at removing harmful toxins from the air, such as formaldehyde, benzene, and toluene.",
    img: "images/img-12.png",
  },
];
